name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: build
        run: "gradle clean shadowjar -p app"
      - name: Test
        run: ci/unit-test-app.sh
      - name: upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: all code
          path: ../../../github-action-katas